version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      - /home/aedion/containers/jellyfin/config:/config
      - /home/aedion/containers/jellyfin/cache:/cache
      - /path/to/media:/data/tvshows
      - /path/to/media2:/data/movies
      - /path/to/media2:/data/youtubevideos
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped