version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=,my puid
      - PGID=,mypgid
      - APP_URL=bookstack.thurlownet.com
      - DB_HOST=bookstack_db
      - DB_USER=aedion
      - DB_PASS=<password>
      - DB_DATABASE=bookstackapp
    volumes:
      - /home/aedion/containers/bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<yourdbpass>
      - TZ=America/New_York
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=<yourdbpass>
    volumes:
      - /home/aedion/containers/bookstack/config:/config
    restart: unless-stopped